Repository funnyzak/react-native-v2ex, pull requests merged in 2022-08, with the labels that each got.

#77 增加NPM命令
  package-lock.json
  package.json
  yarn.lock
Labels: refactor, feature

#78 升级第三方依赖版本到最新
  .gitignore
  Gemfile
  babel.config.js
  ios/Podfile.lock
  ios/app.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  yarn.lock
Labels: refactor

#79 升级ReactNative基础框架到 0.69.4 稳定版
  .flowconfig
  .gitignore
  .ruby-version
  .vscode/settings.json
  README.md
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/github/funnyzak/v2ex/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/github/funnyzak/v2ex/MainActivity.java
  android/app/src/main/java/github/funnyzak/v2ex/MainApplication.java
  android/app/src/main/java/github/funnyzak/v2ex/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/github/funnyzak/v2ex/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/github/funnyzak/v2ex/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/_xcode.env
  ios/app.xcodeproj/project.pbxproj
  ios/app/AppDelegate.mm
  ios/app/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/app/Info.plist
  ios/app/main.m
  ios/appTests/appTests.m
  package.json
  patches/react-native-easy-toast+2.0.0.patch
  yarn.lock
Labels: refactor, feature, dependencies

#80 typo: 修改登陆到登录
  src/i18n/locales/zh.json
  src/store/types.ts
Labels: refactor

#81 Enable Proguard
  android/app/build.gradle
Labels: refactor

#84 fixed: weblink bug
  src/screens/common/WebLink.tsx
Labels: bug

#86 add github app stale
  .github/stale.yml
Labels: refactor

#87 Create FUNDING.yml
  .github/FUNDING.yml
Labels: chore
